/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_genepattern_drm_util_Env */

#ifndef _Included_org_genepattern_drm_util_Env
#define _Included_org_genepattern_drm_util_Env
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_genepattern_drm_util_Env
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_genepattern_drm_util_Env_setenv
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
